name: Test & Deploy
on: 
    workflow_dispatch:
    push:
        branches: main
        paths-ignore: './github/workflows/*'
env: 
    PORT: 4000
jobs:
    test:
        environment: Testing
        runs-on: ubuntu-latest
        container:
            image: node:20
        services:
            mysqldb:
                image: mysql
                env:
                    MYSQL_HOSTNAME: ${{ secrets.MYSQL_HOSTNAME }}
                    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                    MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
                    MYSQL_DB: ${{ secrets.MYSQL_DB }}
                    MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-deps-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Run test
              run: npm run test --if-present
    
    report: 
        needs: [test]
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: |
                echo "Something went wrong..."
                echo "${{ toJson(github) }}"